### PR TITLE
components/display_boxes

### PR DESCRIPTION
**Pull request by hmrbcnto**
- added display box component for displaying previous choices
- added student review form component to display information from Screening and Application form

### CODE REVIEW

**Comment by hmrbcnto** [comment]
- added additional font size, font weight, and padding to mobile view of dropdown boxes
Screen Shot 2022-10-24 at 5 53 13 PM

**Comment by patrickjameslim** [comment]
@hmrbcnto This looks great! The only thing I will recommend is to increase the padding-x. I assume right now it's around 8px? We can try increasing it to 24px. Great work!

**Comment by hmrbcnto** [comment]
- Updated padding cc @patrickjameslim 
Screen Shot 2022-10-25 at 8 25 49 PM

**Review by gerardvcruz — APPROVED** [review]
LGTM

**Pull request merged**
